spring:
  application:
    name: ${SERVER_NAME}

server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: false
    hostname: ${SERVER_NAME}

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  credentials:
    user: ${ELASTICSEARCH_USER}
    password: ${ELASTICSEARCH_PWD}
logging:
  level:
    tracer: TRACE

springdoc:
  api-docs:
    enabled: true 
  swagger-ui: 
    enabled: true